Um 138endpoint shop
Team-Challenge/TC-Back-End pull request #41
Opened 2023-12-06 18:47 UTC by RudychukDmytro

2023-12-08 19:47 UTC, komaxko requested changes

2023-12-08 19:47 UTC, komaxko commented on models/models.py
> +SHOPS_PHOTOS_PATH = os.path.join(Config.MEDIA_PATH, 'shops')
pls add an empty folder in that path and add .gitkeep file in that folder, example: https://github.com/Team-Challenge/TC-Back-End/blob/development/static/media/profile/.gitkeep
(otherwise system will not create such automatically folder and it might crash).

2023-12-08 19:47 UTC, komaxko commented on models/models.py
> +SHOPS_BANNER_PHOTOS_PATH = os.path.join(Config.MEDIA_PATH, 'banner_shops')
pls add an empty folder in that path and add .gitkeep file in that folder, example: https://github.com/Team-Challenge/TC-Back-End/blob/development/static/media/profile/.gitkeep
(otherwise system will not create such automatically folder and it might crash).

2023-12-08 19:47 UTC, komaxko commented on routes/shops_route.py
> +    user = User.query.filter_by(id=current_user_id).first()
can we add a classmethod in User model? this line of code happens quite frequent so would be better to reuse a classmethod.

2023-12-08 19:47 UTC, komaxko commented on routes/shops_route.py
> +    existing_shop = Shop.query.filter_by(owner_id=user.id).first()
we can use classmethod get_shop_by_owner_id here, would be better.

2023-12-08 19:47 UTC, komaxko commented on routes/shops_route.py
> +    shop = Shop.query.filter_by(owner_id=user.id).first()
same here: get_shop_by_owner_id classmethod call

2023-12-08 19:47 UTC, komaxko commented on routes/shops_route.py
> +    user = User.query.filter_by(id=current_user_id).first()
and here again would be better to use User model classmethod to get record if such exists

2023-12-08 19:47 UTC, komaxko commented on routes/shops_route.py
> +    user = User.query.filter_by(id=current_user_id).first()
same here

2023-12-08 19:47 UTC, komaxko commented on routes/shops_route.py
> +    shop = Shop.query.filter_by(owner_id=user.id).first()
same here

2023-12-08 19:47 UTC, komaxko commented on routes/shops_route.py
> +    user = User.query.filter_by(id=current_user_id).first()
same here

2023-12-08 20:45 UTC, RudychukDmytro commented on routes/shops_route.py
> +    user = User.query.filter_by(id=current_user_id).first()
Done

2023-12-08 20:45 UTC, RudychukDmytro commented on routes/shops_route.py
> +    existing_shop = Shop.query.filter_by(owner_id=user.id).first()
Done

2023-12-08 20:45 UTC, RudychukDmytro commented on routes/shops_route.py
> +    shop = Shop.query.filter_by(owner_id=user.id).first()
Done

2023-12-08 20:47 UTC, RudychukDmytro commented on routes/shops_route.py
> +    user = User.query.filter_by(id=current_user_id).first()
Done

2023-12-08 20:47 UTC, RudychukDmytro commented on routes/shops_route.py
> +    user = User.query.filter_by(id=current_user_id).first()
Done

2023-12-08 20:48 UTC, RudychukDmytro commented on routes/shops_route.py
> +    shop = Shop.query.filter_by(owner_id=user.id).first()
Done

2023-12-08 20:48 UTC, RudychukDmytro commented on routes/shops_route.py
> +    user = User.query.filter_by(id=current_user_id).first()
Done

2023-12-08 21:20 UTC, RudychukDmytro commented on models/models.py
> +SHOPS_PHOTOS_PATH = os.path.join(Config.MEDIA_PATH, 'shops')
I used the schema from .gitkeep

2023-12-08 21:20 UTC, RudychukDmytro commented on models/models.py
> +SHOPS_BANNER_PHOTOS_PATH = os.path.join(Config.MEDIA_PATH, 'banner_shops')
I used the schema from .gitkeep

2023-12-11 09:16 UTC, komaxko commented
waiting for @Andrii-Lopukh QA to test this branch locally and his review.

2023-12-11 09:18 UTC, komaxko approved these changes
Now it's @Andrii-Lopukh turn to test again the latest changes before complete this PR

2023-12-12 16:13 UTC, merged