update DB
Team-Challenge/TC-Back-End pull request #57
Opened 2024-01-10 17:44 UTC by RudychukDmytro

The old database model did not meet our current requirements and contained tables that are not currently used and in the future needed a complete update, so the tables that are not used were deleted and the tables that we need for use now were completely updated. To make changes on the server, you must delete the old database before closing the PR

2024-01-11 19:01 UTC, komaxko requested changes
1. move file `patterns.py` from `config` into `models` directory.
2. rename one existing migration prefix to `_init.py` 
3. extend migration file to rename existing tables with `_temp` prefix, create tables new tables, migrate data from temp tables into permanent, drop temp tables.

2024-01-12 10:28 UTC, RudychukDmytro commented
I return all migration files. The new migration file does not involve deleting the old database.

2024-01-15 20:27 UTC, RudychukDmytro commented
The approach of creating a new database and transferring information from the old database was used.
List of necessary steps:
1 Stop server
2 File data/app.db rename to old.db
3 Execute the command "flask db upgrade" (the database will be created and the migration will be performed)
4 Execute the command "python data/restore_data.py" (data will be transferred from the old database to the newly created one)

2024-01-16 11:46 UTC, komaxko approved these changes

2024-01-16 11:48 UTC, merged